Quizzy/Blog/urls.py
from django.urls import path
from Blog.views import *

urlpatterns = [
    path('', PostlistView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view()),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/', add_comment_to_post, name='add_comment_to_post'),
    #path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
]

Quizzy/Quizzy/urls.py
from django.contrib import admin
from django.urls import path, include
from Tests.views import *
from Users.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('contact/', contact, name="contact"),
    path('tests/', include('Tests.urls')),
    path('users/', include('Users.urls')),
    path('blogs/', include('Blog.urls')),
    #path('blog/', include('my_app.urls'))
    #path('que/', que, name='que'),
    path('result/', result, name="result"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quizzy/Users/urls.py
from django.urls import path
from Users.views import *

urlpatterns = [
    path('register/', register, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('profile/', profile_update, name="profile"),
    #path('profile/', profile, name="profile"),
]

Quizzy/Tests/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Topic(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class TestsGiven(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=1)
    score = models.IntegerField(default=0)
    total_score = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    answer_given = models.CharField(max_length=100)
    # questions = models.ManyToOneField(Question, on_delete=models.CASCADE, default=1)
    # attempts = models.IntegerField(default=0)

    def __str__(self):
        if self.name == "":
            return self.topic.name+ " -\t" + str(self.id)
        return self.name


class Question(models.Model):
    text = models.CharField(max_length=100)
    option1 = models.CharField(max_length=100, blank=True, null=True)
    option2 = models.CharField(max_length=100, blank=True, null=True)
    option3 = models.CharField(max_length=100, blank=True, null=True)
    option4 = models.CharField(max_length=100, blank=True, null=True)
    marks = models.IntegerField(default=0)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=1)
    related_answer = models.CharField(max_length=100, blank=True, null=True)
    # score = models.IntegerField(default=0)
    # test = models.ForeignKey(TestsGiven, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.text

    def calculate_score(self):
        pass

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True, default=1)
    user_selected_answer = models.CharField(max_length=100)
    right_answer = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user_selected_answer

Quizzy/Users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image
# Create your models here.
User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    # uploads image to Profile_Pictures dir inside project directory
    image = models.ImageField(default='default.jpg', upload_to = 'Profile_Pictures')

    def __str__(self):
        return self.user.username

    # To resize the Image
    # def save(self):
    #     super().save()
    #     img = Image.open(self.image.path)
    #
    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

Quizzy/Users/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import *

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100,
                widget=forms.TextInput(attrs={"placeholder":"Username"}))
    password = forms.CharField(max_length=100,
                widget=forms.PasswordInput(attrs={"placeholder":"Password"}))

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=100,
                widget=forms.TextInput(attrs={"placeholder":"Username", "class":"form-control"}))
    email = forms.EmailField(
                widget=forms.TextInput(attrs={"placeholder":"Email", "class":"form-control"}))
    password1 = forms.CharField(label="Password", max_length=100,
                widget=forms.PasswordInput(attrs={"placeholder":"Password", "class":"form-control"}))
    password2 = forms.CharField(label="Confirm Password", max_length=100,
                widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password", "class":"form-control"}))


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

Quizzy/Users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate, get_user_model
from .forms import LoginForm, RegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib import messages
# Create your views here.
User = get_user_model()

def login_view(request):
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid():
        username = login_form.cleaned_data.get('username')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, "Please Check Your Credentials Again !")
            return redirect('login')
    return render(request, 'Users/form.html', {'form':login_form})


def logout_view(request):
    logout(request)
    return render(request, 'Users/logout.html',{})

def register(request):
    register_form = RegisterForm(request.POST or None)
    if register_form.is_valid():
        usn = register_form.cleaned_data.get('username')
        email = register_form.cleaned_data.get('email')
        pwd1 = register_form.cleaned_data.get('password1')
        pwd2 = register_form.cleaned_data.get('password2')
        # user = User.objects.create_user(usn, email, pwd1)
        try:
            if pwd1 == pwd2:
                user = User.objects.create_user(usn, email, pwd1)
                messages.success(request, f'Account Created For {usn}!')
                return redirect('register')
            else:
                messages.error(request, "Please Check Your Credentials Again !")
        except:
            user = None
    return render(request, 'Users/signup.html',{'form':register_form})


@login_required
def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance = request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('profile')
    user_form = UserUpdateForm(instance = request.user)
    profile_form = ProfileUpdateForm(instance = request.user.profile)
    return render(request, 'Users/profile.html', {'user_form':user_form, 'profile_form':profile_form})


# @login_required
# def profile(request):
#     return render(request, 'Users/profile.html', {})

Quizzy/Users/templates/Users/base.html
{% load static %}
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login and SignUp - Quizzy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <style>
      body{
        background-image: url({% static 'images/puz.jpg' %});
        background-repeat: no-repeat;
      }
    </style>
  </head>
  <body style="background-color:#00b8e6;">
    <div>
      <ul class="navbar">
        <li><a class="active" href="{% url 'home' %}">Quizzy</a></li>

        <li style="float:left"><a href="{% url 'contact' %}">Contact</a></li>
        <li style="float:left"><a href="{% url 'blog-home' %}">Read Blogs</a></li>
        {% if request.user.is_authenticated %}
          <li style="float:right;"><a href="{% url 'profile' %}">Profile</a> </li>
          <li style="float:right;"><a href="{% url 'logout' %}">{{request.user}} &nbsp;|&nbsp; Logout</a></li>
        {% else %}
          <li style="float:right;"><a href="{% url 'login' %}">Login</a></li>
          <li style="float:right;"><a href="{% url 'register' %}">Join For Free</a></li>
        {% endif %}
      </ul>
    </div>
    {% block login %}
    {% endblock %}
  </body>
</html>

Quizzy/Users/templates/Users/form.html
{% extends 'Users/base.html' %}
{% load crispy_forms_tags %}
{% block login %}


<div class="loginpage">
  <p style="font-size:1.5rem; padding:20px 20px 10px 50px;">Join Here and Start Practicing !</p>
  <form method="POST" class="form_page">
    {% csrf_token %}
    <!-- {{ form|crispy }}<br> -->
    {{form.username}}<br>
    {{form.password}}<br>
    <input type="submit"  class="btn btn-primary" value="Log In"><br><br>
    Need an Account ? <a class="ml-4" href="{% url 'register' %}">Sign Up</a>
  </form>
  {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{message.tags}}" style="width:300px; margin-left:90px; text-align:center;">
        {{ message }}
      </div>
      {% endfor %}
  {% endif %}
</div>
{% endblock %}

Quizzy/Users/templates/Users/logout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Questions - {% endblock %}
{% block content %}
  <p>You have been Logged Out</p>
  <a href="{% url 'login' %}">Login Again</a>

{% endblock %}

Quizzy/Users/templates/Users/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Profile - {% endblock %}
{% block content %}
    <div class="content-section pt-2">
        <div style="float:left;">
          <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="not found">
        </div>
        <div style="float:right;padding-left: 100px;">
          <h2 class="account-heading">{{user.username}}</h2>
          <p class="text-secondary">{{user.email}}</p>
          {% if request.user.is_staff %}
            <a href="{% url 'add_question'%}" class="btn btn-danger" style="float:right; margin-right:20px;">Add New Question</a>
            <a href="{% url 'question_list'%}" class="btn btn-danger" style="float:right; margin-right:20px;">See All Questions</a>
          {% endif %}
          <a href="{% url 'tests_given' user.id %}" class="btn btn-danger" style="float:right; margin-right:20px;">See All Tests</a>
        </div>
    </div><br>
    <form style="padding-top:160px;" method="POST" class="form_page" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form|crispy }}<br>
      {{ profile_form|crispy }}<br>
      <input type="submit"  class="btn btn-primary" value="Update">
    </form>
{% endblock %}

Quizzy/Users/templates/Users/signup.html
{% extends 'Users/base.html' %}
{% load crispy_forms_tags %}
{% block login %}
<div class="loginpage" style="height:550px;">
      <p style="font-size:1.5rem; padding:0px 0px 0px 50px;">Join Here and Start Practicing !</p>
      <form method="POST" class="form_page">
        {% csrf_token %}
        {{ form.username }}<br>
        {{ form.email }}<br>
        {{ form.password1 }}<br>
        {{ form.password2 }}<br>
        <input type="submit" style="margin-right:40px;" class="btn btn-primary" value="Sign up">
        Already Have an Account ? <a href="{% url 'login' %}">Login</a>
      </form>
      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{message.tags}}" style="width:300px; margin-left:90px; text-align:center;">
            {{ message }}
          </div>
          {% endfor %}
      {% endif %}
</div>
{% endblock %}

Quizzy/Users/templates/Users/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Update - {% endblock %}
{% block content %}
  <form method="POST" class="form_page" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form|crispy }}<br>
    {{ profile_form|crispy }}<br>
    <input type="submit"  class="btn btn-primary" value="Update">
  </form>
{% endblock %}