Quizzy/Blog/urls.py
from django.urls import path
from Blog.views import *

urlpatterns = [
    path('', PostlistView.as_view(), name='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view()),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:pk>/comment/', add_comment_to_post, name='add_comment_to_post'),
    #path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
]

Quizzy/Quizzy/urls.py
from django.contrib import admin
from django.urls import path, include
from Tests.views import *
from Users.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('contact/', contact, name="contact"),
    path('tests/', include('Tests.urls')),
    path('users/', include('Users.urls')),
    path('blogs/', include('Blog.urls')),
    #path('blog/', include('my_app.urls'))
    #path('que/', que, name='que'),
    path('result/', result, name="result"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Quizzy/Blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from Tests.models import Topic

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=1000)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    published_date = models.DateTimeField(blank=True,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.pk})


# class Comment(models.Model):
#     post = models.ForeignKey('Blog.Post',related_name='comments',on_delete=models.CASCADE)
#     author = models.CharField(max_length=200)
#     text = models.TextField()
#     create_date = models.DateTimeField(default=timezone.now)
#
#     def get_absolute_url(self):
#         return reverse('post_list')
#
#     def __str__(self):
#         return self.text

Quizzy/Tests/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Topic(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class TestsGiven(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=1)
    score = models.IntegerField(default=0)
    total_score = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    answer_given = models.CharField(max_length=100)
    # questions = models.ManyToOneField(Question, on_delete=models.CASCADE, default=1)
    # attempts = models.IntegerField(default=0)

    def __str__(self):
        if self.name == "":
            return self.topic.name+ " -\t" + str(self.id)
        return self.name


class Question(models.Model):
    text = models.CharField(max_length=100)
    option1 = models.CharField(max_length=100, blank=True, null=True)
    option2 = models.CharField(max_length=100, blank=True, null=True)
    option3 = models.CharField(max_length=100, blank=True, null=True)
    option4 = models.CharField(max_length=100, blank=True, null=True)
    marks = models.IntegerField(default=0)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=1)
    related_answer = models.CharField(max_length=100, blank=True, null=True)
    # score = models.IntegerField(default=0)
    # test = models.ForeignKey(TestsGiven, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.text

    def calculate_score(self):
        pass

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True, default=1)
    user_selected_answer = models.CharField(max_length=100)
    right_answer = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user_selected_answer

Quizzy/Blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['author','title','topic','content']

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass form-control'}),
            'content':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent form-control'})
        }

# class CommentForm(forms.ModelForm):
#
#     class Meta:
#         model = Comment
#         fields = ['text']
#
#         widgets = {
#             'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
#         }

Quizzy/Blog/views.py
from django.shortcuts import render, get_object_or_404
from Blog.models import Post
from Blog.forms import PostForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (ListView,DetailView,
                                CreateView,UpdateView, DeleteView)
# Create your views here.

class PostlistView(ListView):
    model = Post
    template_name = 'Blog/blog-home.html'
    ordering = ['-date_posted']
    context_object_name = 'posts'

class PostDetailView(DetailView):
    model = Post
    template_name = 'Blog/blog-detail.html'

class UserPostListView(ListView):
    model = Post
    template_name = 'Blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author = user).order_by('-date_posted')

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','topic','content']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','content']

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('post-detail',pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'Blog/comment_form.html',{'form':form})


@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post-detail',pk=post_pk)

Quizzy/Blog/templates/Blog/base-template.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}Quizzy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <style>{% block style %}{% endblock %}</style>
  </head>
  <body>
    <div>
      <ul class="navbar">
        <li><a class="active" href="{% url 'home' %}">Quizzy</a></li>
        <li style="float:left"><a href="{% url 'contact' %}">Contact</a></li>
        <li style="float:left"><a href="{% url 'topic_list' %}">Take Quiz</a></li>
        {% if request.user.is_authenticated %}
          <li style="float:right;"><a href="{% url 'post-create' %}">New Post</a> </li>
          <li style="float:right;"><a href="{% url 'profile' %}">Profile</a> </li>
          <li style="float:right;"><a href="{% url 'logout' %}">{{request.user}} &nbsp;|&nbsp; Logout</a></li>
        {% else %}
          <li style="float:right;"><a href="{% url 'login' %}">Login</a></li>
          <li style="float:right;"><a href="{% url 'register' %}">Join For Free</a></li>
        {% endif %}
      </ul>
    </div>

    <div class="container content">
          <div class="row">
            <div class="col-md-8">
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4">
              <div class="sidebar">
                <ul class="list-group">
                  <article class="media">
                  </article>
                </ul>
              </div>
            </div>
          </div>
        </div>

  </body>
  <script type="text/javascript">

    document.querySelector('#btnevent').addEventListener('click', promptMe);

    function promptMe() {
        alert("Please Sign In First")
    }
  </script>
  {% block script %}
  {% endblock %}
</html>

Quizzy/Blog/templates/Blog/blog-detail.html
{% extends 'Blog/base-template.html'%}
{% block content %}
  <h2>Welcome, {{ user }} !</h2><br>
  <article class="media">
    <img class="rounded-circle" style="height:100px; width:100px; float:left; margin-right:30px;" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
        <div>
          <a href="{% url 'post-update' object.id %}" class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
          <a href="{% url 'post-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1">Delete</a>
        </div>
          {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}
      </p>
      {% if user.is_authenticated %}
        <a class="btn btn-primary btn-comment" href="{% url 'add_comment_to_post' pk=post.pk %}">Add Comments</a><br><br>
      {% endif %}
    </div>
  </article>
  <div class="container" style="border : 1px solid #b3e0ff;">
    <p>Comments:</p>
    {% for comment in post.comments.all %}
        <h6>{{comment.author}}</h6>
        <h5>{{comment.text|safe|linebreaks}}</h5>
        <hr>
        {% if user.is_authenticated and object.author == user %}
              <a class="btn btn-primary" href="{% url 'comment_remove' pk=comment.pk %}">
                <span class="glyphicon glyphicon-remove">Remove</span>
              </a>
        {% endif %}
      {% empty %}
        <p>No Comments! </p>
    {% endfor %}
  </div>
  {% endblock %}

Quizzy/Blog/templates/Blog/blog-home.html
{% extends 'Blog/base-template.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
      {% for post in posts %}
        <article class="media" style="border-bottom: 1px solid #b3e0ff; padding: 10px 0px 10px 0px;">
          <img class="rounded-circle" style="height:100px; width:100px; float:left;" src="{{ post.author.profile.image.url }}">
          <div class="media-body" style="padding-left:20px; margin-left:100px;">
            <div class="article-metadata">
              <i class="mr-2">By {{ post.author }}</i>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h5><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h5>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
      {% endfor %}
{% endblock %}

Quizzy/Blog/templates/Blog/comment_form.html
{% extends "Blog/base-template.html" %}
{% block content %}
  <h1>New Comment</h1>
  <form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-outline-primary">Post Comment</button>
  </form>
{% endblock %}

Quizzy/Blog/templates/Blog/post_confirm_delete.html
{% extends 'Blog/base-template.html' %}
{% block content %}
  <div class="content-section">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h2>Arre you sure you want to delete the post "{{ object.title }}"?</h2>
      </fieldset>
      <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Yes, Delete!</button>
        <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel!</a>

      </div>
    </form>
  </div>
{% endblock %}

Quizzy/Blog/templates/Blog/post_form.html
{% extends 'Blog/base-template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Blog Post</legend>
        <!-- {{ form|crispy }} -->
        <label for="">Title</label>{{form.title}}
        <label for="">Topic</label>{{form.topic}}
        <label for="">Content</label>{{form.content}}
      </fieldset>
      <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Post!</button>
      </div>
    </form>
  </div>
{% endblock %}

Quizzy/Blog/templates/Blog/user_posts.html
{% extends 'Blog/base-template.html'%}
{% block content %}
  <h3 class="mb-3">Posts by: {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h3>
  {% for post in posts %}
    <article class="media" style="border-bottom: 1px solid #b3e0ff;">
      <img class="rounded-circle" style="height:100px; width:100px; float:left; margin-right:30px;" src="{{ post.author.profile.image.url }}">
      <div class="media-body" style="padding-left:20px; margin-left:130px;">
        <div class="article-metadata">
          <i>{{ post.author }}</i>
          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
        </div>
        <h3><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h3>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
  {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock %}